[package]
name = "grpc-client"
description = "grpc-client."
version = "0.0.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
repository = "https://github.com/andrewhickman/grpc-client"
documentation = "https://docs.rs/grpc-client"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
build = "build.rs"

[dependencies]
anyhow = "1.0.38"
log = "0.4.13"
futures = "0.3.12"
serde_json = "1.0.61"
bytes = "1.0.1"
http = "0.2.3"
fs-err = "2.5.0"
once_cell = "1.5.2"
memchr = "2.3.4"
serde-transcode = "1.1.0"
iter-set = "2.0.1"
env_logger = "0.8.2"
dirs-next = "2.0.0"
tokio-stream = "0.1.2"
open = "1.4.0"

[dependencies.druid]
version = "0.7.0"
features = ["im", "svg"]

[dependencies.protobuf]
git = "https://github.com/andrewhickman/rust-protobuf.git"
rev = "666318a6febd2a7b894116848fa1ff5c8d08bf3f"
features = ["with-serde"]

[dependencies.tonic]
version = "0.4.0"
default-features = false
features = ["transport", "tls", "tls-roots"]

[dependencies.tokio]
version = "1.0.2"
features = ["macros", "rt-multi-thread", "sync"]

[dependencies.syntect]
version = "4.5.0"
default-features = false
features = ["parsing", "regex-onig", "assets", "dump-load"]

[dependencies.serde]
version = "1.0.119"
features = ["derive", "rc"]

[dependencies.kurbo] 
version = "0.7.1"
features = ["serde"]

[dependencies.im]
version = "15.0.0"
features = ["serde"]

[build-dependencies]
vergen = "3.1.0"
