[package]
name = "grpc-client"
description = "grpc-client."
version = "0.0.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
repository = "https://github.com/andrewhickman/grpc-client"
documentation = "https://docs.rs/grpc-client"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
anyhow = "1.0.32"
log = "0.4.11"
futures = "0.3.5"
serde_json = "1.0.57"
bytes = "0.5.6"
http = "0.2.1"
fs-err = "2.3.0"
im = "15.0.0"

[dependencies.druid]
git = "https://github.com/linebender/druid"
rev = "694af59d63318c7197f81eedba56de3071182321"
features = ["im"]

[dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf.git"
rev = "b447f53014af46a7faf6bf46d313391a61b2eace"

[dependencies.tonic]
version = "0.3.0"
default-features = false
features = ["transport", "tls", "tls-roots"]

[dependencies.tokio]
version = "0.2.22"
features = ["macros", "rt-threaded", "sync"]
