[package]
name = "grpc-client"
description = "grpc-client."
version = "0.0.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
repository = "https://github.com/andrewhickman/grpc-client"
documentation = "https://docs.rs/grpc-client"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
build = "build.rs"

[dependencies]
anyhow = "1.0.38"
futures = "0.3.12"
serde_json = "1.0.62"
bytes = "1.0.1"
http = "0.2.3"
fs-err = "2.5.0"
once_cell = "1.5.2"
memchr = "2.3.4"
serde-transcode = "1.1.0"
iter-set = "2.0.1"
dirs-next = "2.0.0"
tokio-stream = "0.1.3"
open = "1.4.0"
tracing-subscriber = "0.2.15"
tracing = "0.1.23"

[dependencies.druid]
git = "https://github.com/linebender/druid.git"
branch = "master"
features = ["im", "svg", "serde"]

[dependencies.protobuf]
git = "https://github.com/andrewhickman/rust-protobuf.git"
branch = "master"
features = ["with-serde"]

[dependencies.tonic]
version = "0.4.0"
default-features = false
features = ["transport", "tls", "tls-roots"]

[dependencies.tokio]
version = "1.2.0"
features = ["macros", "rt-multi-thread", "sync"]

[dependencies.syntect]
version = "4.5.0"
default-features = false
features = ["parsing", "regex-onig", "assets", "dump-load"]

[dependencies.serde]
version = "1.0.123"
features = ["derive", "rc"]

[dependencies.kurbo] 
version = "0.8.1"
features = ["serde"]

[dependencies.im]
version = "15.0.0"
features = ["serde"]

[build-dependencies]
anyhow = "1.0.40"

[build-dependencies.vergen]
version = "5.1.0"
default-features = false
features = ["git"]
